#!/usr/bin/env bash
# SLOPE guard dispatcher — routes hook events to slope guard handlers
# Auto-generated by slope hook add --level=full

# === SLOPE MANAGED (do not edit above this line) ===
slope guard "$@" < /dev/stdin
# === SLOPE END ===
