#!/usr/bin/env bash
# SLOPE guard dispatcher — routes hook events to slope guard handlers
# Auto-generated by slope hook add --level=full

# === SLOPE MANAGED (do not edit above this line) ===
# Note: Do NOT use `< /dev/stdin` — on WSL2 the /dev/stdin redirect
# can fail when Claude Code pipes hook input. Use inherited stdin directly.
node /home/srbryers/slope/dist/cli/index.js guard "$@"
# === SLOPE END ===
