import { execSync, execFileSync } from 'node:child_process';
import type { LoopConfig, TicketResult } from './types.js';
import type { Logger } from './logger.js';

export interface PrInfo {
  url: string;
  number: number;
}

export interface MergeResult {
  merged: boolean;
  blockReason?: string;
}

/** Check if gh CLI is available and authenticated */
export function checkGhCli(log: Logger): boolean {
  try {
    execFileSync('gh', ['--version'], { stdio: 'pipe' });
  } catch {
    log.warn('gh CLI not found — PR creation will be skipped');
    return false;
  }
  try {
    execFileSync('gh', ['auth', 'status'], { stdio: 'pipe' });
  } catch {
    log.warn('gh CLI not authenticated — PR creation will be skipped');
    return false;
  }
  return true;
}

/** Check if branch has commits ahead of main */
export function hasCommitsAhead(branch: string, cwd: string): boolean {
  try {
    const count = execFileSync('git', ['rev-list', '--count', `main..${branch}`], {
      cwd,
      encoding: 'utf8',
    }).trim();
    return parseInt(count, 10) > 0;
  } catch {
    return false;
  }
}

/** Create a PR for the sprint branch */
export function createPr(
  branch: string,
  sprintId: string,
  title: string,
  strategy: string,
  ticketResults: TicketResult[],
  cwd: string,
  log: Logger,
): PrInfo | null {
  const passingCount = ticketResults.filter(t => t.tests_passing && !t.noop).length;
  const noopCount = ticketResults.filter(t => t.noop).length;
  const totalCount = ticketResults.length;

  const ticketLines = ticketResults.map(t => {
    const status = t.noop ? 'no-op' : t.tests_passing ? 'pass' : 'fail';
    const modelShort = t.final_model.split('/').pop();
    return `- **${t.ticket}**: ${t.title} — ${status} (${modelShort})`;
  }).join('\n');

  const body = `## Sprint ${sprintId} — ${title}

**Strategy:** ${strategy} | **Tickets:** ${totalCount} | **Passing:** ${passingCount} | **No-ops:** ${noopCount}

### Tickets
${ticketLines}

### Verification
- Tests: ${passingCount > 0 ? 'passing' : 'failing'}
- Generated by autonomous loop (\`slope loop run\`)`;

  try {
    const url = execFileSync('gh', [
      'pr', 'create',
      '--base', 'main',
      '--head', branch,
      '--title', `feat(${sprintId}): ${title}`,
      '--body', body,
    ], { cwd, encoding: 'utf8' }).trim();
    const number = parseInt(url.match(/\d+$/)?.[0] ?? '0', 10);
    log.info(`PR created: ${url} (PR #${number})`);
    return { url, number };
  } catch (err) {
    log.warn(`PR creation failed: ${(err as Error).message}`);
    return null;
  }
}

/**
 * Run structural review on a PR diff.
 * Returns number of findings added.
 */
export function runStructuralReview(
  prNumber: number,
  sprintId: string,
  sprintNum: number,
  cwd: string,
  log: Logger,
): number {
  let findingCount = 0;

  let diff: string;
  try {
    diff = execFileSync('gh', ['pr', 'diff', String(prNumber)], { cwd, encoding: 'utf8' });
  } catch {
    log.warn('Could not fetch PR diff');
    return 0;
  }

  // Track current file context for file-aware checks
  let currentFile = '';
  const addedLines: string[] = [];
  const prodAddedLines: string[] = [];
  const changedFiles: string[] = [];

  for (const line of diff.split('\n')) {
    if (line.startsWith('diff --git')) {
      currentFile = line.replace(/.*b\//, '');
      changedFiles.push(currentFile);
    }
    if (line.startsWith('+') && !line.startsWith('+++')) {
      addedLines.push(line);
      // Only track production lines (not test files)
      if (!currentFile.endsWith('.test.ts') && !currentFile.endsWith('.spec.ts')) {
        prodAddedLines.push(line);
      }
    }
  }

  const changedTsFiles = changedFiles.filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts') && !f.endsWith('.d.ts'));
  const changedTestFiles = changedFiles.filter(f => f.endsWith('.test.ts'));

  // Check 1: Type escapes
  const typeEscapes = addedLines.filter(l => /as any|@ts-ignore|@ts-expect-error/.test(l)).length;
  if (typeEscapes > 0) {
    addFinding('code', sprintId, sprintNum, 'minor', `${typeEscapes} type escape(s) found (as any / @ts-ignore)`, cwd, log);
    findingCount++;
  }

  // Check 2: Console.log in production code (excludes test files)
  const prodConsoleLogs = prodAddedLines.filter(l => /console\.log/.test(l)).length;
  if (prodConsoleLogs > 0) {
    addFinding('code', sprintId, sprintNum, 'minor', `${prodConsoleLogs} console.log statement(s) in production code`, cwd, log);
    findingCount++;
  }

  // Check 3: Source files changed without test changes
  let untestedCount = 0;
  for (const srcFile of changedTsFiles) {
    const baseName = srcFile.replace(/\.ts$/, '');
    if (!changedTestFiles.some(t => t.includes(baseName.split('/').pop() + '.test.ts'))) {
      untestedCount++;
    }
  }
  if (untestedCount > 0) {
    addFinding('code', sprintId, sprintNum, 'moderate', `${untestedCount} source file(s) changed without corresponding test changes`, cwd, log);
    findingCount++;
  }

  // Check 4: Security-sensitive file changes
  const securityFiles = changedFiles.filter(f => /auth\/|oauth|jwt|secret|crypto|password|credential/i.test(f));
  if (securityFiles.length > 0) {
    addFinding('security', sprintId, sprintNum, 'moderate', `${securityFiles.length} security-sensitive file(s) changed`, cwd, log);
    findingCount++;
  }

  // Check 5: Large file diffs (>500 additions per file)
  try {
    const filesJson = execFileSync('gh', [
      'pr', 'view', String(prNumber),
      '--json', 'files',
      '--jq', '[.files[] | select(.additions > 500)] | .[].path',
    ], { cwd, encoding: 'utf8' }).trim();
    if (filesJson) {
      const largeCount = filesJson.split('\n').filter(Boolean).length;
      if (largeCount > 0) {
        addFinding('architect', sprintId, sprintNum, 'minor', `${largeCount} file(s) with >500 lines added`, cwd, log);
        findingCount++;
      }
    }
  } catch { /* ok — gh view might fail */ }

  return findingCount;
}

function addFinding(
  type: string,
  sprintId: string,
  sprintNum: number,
  severity: string,
  description: string,
  cwd: string,
  log: Logger,
): void {
  try {
    execFileSync('pnpm', [
      'slope', 'review', 'findings', 'add',
      `--type=${type}`,
      `--ticket=${sprintId}-0`,
      `--severity=${severity}`,
      `--description=${description}`,
      `--sprint=${String(sprintNum)}`,
    ], { cwd, stdio: 'pipe' });
  } catch {
    log.warn(`Failed to add finding: ${description}`);
  }
}

/**
 * Run auto-merge safeguards and merge if all pass.
 */
export function autoMerge(
  prNumber: number,
  findingCount: number,
  passingCount: number,
  config: LoopConfig,
  cwd: string,
  log: Logger,
): MergeResult {
  // Safeguard 1: No critical/major findings
  if (findingCount > 0) {
    try {
      const findingsList = execFileSync('pnpm', ['slope', 'review', 'findings', 'list'], {
        cwd, encoding: 'utf8',
      });
      const criticalMajor = (findingsList.match(/\b(critical|major)\b/g) || []).length;
      if (criticalMajor > 0) {
        return block(prNumber, `${criticalMajor} critical/major finding(s)`, cwd, log);
      }
    } catch {
      // If findings list fails, treat as a merge block (safety-critical path)
      log.warn('Could not verify findings — blocking merge as precaution');
      return block(prNumber, 'findings verification failed', cwd, log);
    }
  }

  // Safeguard 2: Tests pass
  try {
    execSync(config.loopTestCmd, { cwd, stdio: 'pipe', timeout: 300_000 });
  } catch {
    return block(prNumber, 'tests failing', cwd, log);
  }

  // Safeguard 3: Typecheck passes
  try {
    execSync('pnpm typecheck', { cwd, stdio: 'pipe', timeout: 120_000 });
  } catch {
    return block(prNumber, 'typecheck failing', cwd, log);
  }

  // Safeguard 4: PR not too large (<20 files changed)
  try {
    const filesChanged = execFileSync('gh', [
      'pr', 'view', String(prNumber),
      '--json', 'changedFiles',
      '--jq', '.changedFiles',
    ], { cwd, encoding: 'utf8' }).trim();
    const count = parseInt(filesChanged, 10) || 0;
    if (count > 20) {
      return block(prNumber, `${count} files changed (threshold: 20)`, cwd, log);
    }
  } catch { /* ok — proceed if check fails */ }

  // Safeguard 5: At least one passing non-noop ticket
  if (passingCount <= 0) {
    return block(prNumber, 'no passing tickets', cwd, log);
  }

  // All safeguards passed — merge
  log.info('All safeguards passed — auto-merging');
  try {
    execFileSync('gh', ['pr', 'merge', String(prNumber), '--squash', '--delete-branch'], {
      cwd, stdio: 'pipe',
    });
    log.info('PR merged successfully');
    return { merged: true };
  } catch {
    log.warn('Auto-merge failed — merge manually');
    return { merged: false, blockReason: 'merge command failed' };
  }
}

function block(prNumber: number, reason: string, cwd: string, log: Logger): MergeResult {
  log.warn(`Auto-merge blocked: ${reason}`);
  try {
    execFileSync('gh', [
      'pr', 'comment', String(prNumber),
      '--body', `Auto-merge blocked: ${reason}. Manual review required.`,
    ], { cwd, stdio: 'pipe' });
  } catch { /* ok */ }
  return { merged: false, blockReason: reason };
}
