import { execFileSync } from 'node:child_process';
import type { SprintResult } from './types.js';
import type { Logger } from './logger.js';

/**
 * Create a staging branch from main and push to origin.
 * Branch naming: loop/batch-NNN where NNN is the first sprint ID.
 */
export function initStagingBranch(firstSprintId: string, cwd: string, log: Logger): string {
  const branch = `loop/batch-${firstSprintId}`;

  // Ensure we're up to date with main
  try {
    execFileSync('git', ['fetch', 'origin', 'main'], { cwd, stdio: 'pipe' });
  } catch { /* ok — may be offline */ }

  // Create branch from origin/main (not local main which may be stale)
  // If branch already exists (interrupted re-run), reuse it
  try {
    execFileSync('git', ['branch', branch, 'origin/main'], { cwd, stdio: 'pipe' });
  } catch {
    // Check if branch already exists — reuse for idempotent re-runs
    try {
      execFileSync('git', ['rev-parse', '--verify', branch], { cwd, stdio: 'pipe' });
      log.info(`Reusing existing staging branch: ${branch}`);
    } catch {
      throw new Error(`Failed to create staging branch ${branch}`);
    }
  }

  // Push to origin so sprint worktrees can branch from it
  try {
    execFileSync('git', ['push', '-u', 'origin', branch], { cwd, stdio: 'pipe' });
  } catch {
    log.warn('Could not push staging branch to origin — sprint PRs will target local branch');
  }

  log.info(`Staging branch created: ${branch}`);
  return branch;
}

/**
 * Create an umbrella PR from staging branch to main with batch summary.
 */
export function createUmbrellaPr(
  stagingBranch: string,
  sprintResults: SprintResult[],
  cwd: string,
  log: Logger,
): { url: string; number: number } | null {
  // Fetch latest staging ref so local matches remote after sprint merges
  try {
    execFileSync('git', ['fetch', 'origin', `${stagingBranch}:${stagingBranch}`], { cwd, stdio: 'pipe' });
  } catch { /* ok */ }

  // Check if staging has commits ahead of main
  try {
    const count = execFileSync('git', ['rev-list', '--count', `main..${stagingBranch}`], {
      cwd, encoding: 'utf8',
    }).trim();
    if (parseInt(count, 10) === 0) {
      log.info('Staging branch has no commits ahead of main — skipping umbrella PR');
      return null;
    }
  } catch {
    log.warn('Could not check staging branch status');
    return null;
  }

  const totalSprints = sprintResults.length;
  const mergedSprints = sprintResults.filter(r => r.merge_status === 'merged').length;
  const totalTickets = sprintResults.reduce((sum, r) => sum + r.tickets_total, 0);
  const totalPassing = sprintResults.reduce((sum, r) => sum + r.tickets_passing, 0);
  const totalNoop = sprintResults.reduce((sum, r) => sum + r.tickets_noop, 0);

  const sprintRows = sprintResults.map(r => {
    const status = r.merge_status === 'merged' ? 'merged' :
                   r.merge_status === 'blocked' ? 'blocked' : 'skipped';
    const prLink = r.pr_number ? `#${r.pr_number}` : '-';
    return `| ${r.sprint_id} | ${r.title} | ${r.strategy} | ${r.tickets_passing}/${r.tickets_total} | ${r.tickets_noop} | ${status} | ${prLink} |`;
  }).join('\n');

  const body = `## Batch Summary — ${stagingBranch}

**Sprints:** ${totalSprints} (${mergedSprints} merged) | **Tickets:** ${totalPassing}/${totalTickets} passing | **No-ops:** ${totalNoop}

### Sprint Results

| Sprint | Title | Strategy | Pass/Total | Noop | Status | PR |
|--------|-------|----------|-----------|------|--------|-----|
${sprintRows}

### Verification
- Generated by autonomous loop (\`slope loop continuous --staging\`)
- Each sprint passed guards (typecheck + tests) before merge to staging`;

  const sprintIds = sprintResults.map(r => r.sprint_id).join(', ');

  try {
    const url = execFileSync('gh', [
      'pr', 'create',
      '--base', 'main',
      '--head', stagingBranch,
      '--title', `feat(loop): batch ${stagingBranch} (${sprintIds})`,
      '--body', body,
    ], { cwd, encoding: 'utf8' }).trim();

    const number = parseInt(url.match(/\d+$/)?.[0] ?? '0', 10);
    log.info(`Umbrella PR created: ${url} (PR #${number})`);
    return { url, number };
  } catch (err) {
    log.warn(`Umbrella PR creation failed: ${(err as Error).message}`);
    return null;
  }
}

/**
 * Delete staging branch (local + remote). Only deletes if merged.
 */
export function cleanupStagingBranch(stagingBranch: string, cwd: string, log: Logger): boolean {
  // Safe delete — refuses if unmerged
  try {
    execFileSync('git', ['branch', '-d', stagingBranch], { cwd, stdio: 'pipe' });
    log.info(`Deleted local staging branch: ${stagingBranch}`);
  } catch {
    log.info(`Staging branch ${stagingBranch} has unmerged changes — keeping local`);
    return false;
  }

  try {
    execFileSync('git', ['push', 'origin', '--delete', stagingBranch], { cwd, stdio: 'pipe' });
    log.info(`Deleted remote staging branch: ${stagingBranch}`);
  } catch {
    log.info(`Could not delete remote staging branch — may need manual cleanup`);
  }

  return true;
}
