import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { renderVisionMarkdown, writeVisionMarkdown } from '../../src/core/vision.js';
import type { VisionDocument } from '../../src/core/index.js';

function makeVision(overrides: Partial<VisionDocument> = {}): VisionDocument {
  return {
    purpose: 'Test purpose',
    priorities: ['priority a', 'priority b'],
    audience: 'developers',
    techDirection: 'TypeScript + Node',
    nonGoals: ['no-go-1', 'no-go-2'],
    createdAt: '2026-05-07T00:00:00Z',
    updatedAt: '2026-05-07T01:00:00Z',
    ...overrides,
  };
}

describe('renderVisionMarkdown (GH #305)', () => {
  it('renders all sections when fields are populated', () => {
    const md = renderVisionMarkdown(makeVision());
    expect(md).toContain('# Project Vision');
    expect(md).toContain('## Purpose');
    expect(md).toContain('Test purpose');
    expect(md).toContain('## Audience');
    expect(md).toContain('developers');
    expect(md).toContain('## Priorities');
    expect(md).toContain('- priority a');
    expect(md).toContain('## Technical direction');
    expect(md).toContain('## Non-goals');
    expect(md).toContain('- no-go-1');
    expect(md).toContain('_Updated 2026-05-07T01:00:00Z_');
  });

  it('omits optional sections when fields are empty', () => {
    const md = renderVisionMarkdown(makeVision({
      audience: undefined,
      techDirection: undefined,
      nonGoals: [],
    }));
    expect(md).not.toContain('## Audience');
    expect(md).not.toContain('## Technical direction');
    expect(md).not.toContain('## Non-goals');
    expect(md).toContain('## Purpose');
    expect(md).toContain('## Priorities');
  });

  it('includes the regeneration banner', () => {
    const md = renderVisionMarkdown(makeVision());
    expect(md).toContain('Generated by `slope vision create --write-md`');
    expect(md).toContain('.slope/vision.json');
  });
});

describe('writeVisionMarkdown', () => {
  let cwd: string;

  beforeEach(() => { cwd = mkdtempSync(join(tmpdir(), 'slope-vision-md-')); });
  afterEach(() => { rmSync(cwd, { recursive: true, force: true }); });

  it('writes to relative path resolved against cwd', () => {
    const path = writeVisionMarkdown(makeVision(), 'docs/vision.md', cwd);
    expect(path).toBe(join(cwd, 'docs', 'vision.md'));
    expect(existsSync(path)).toBe(true);
    expect(readFileSync(path, 'utf8')).toContain('# Project Vision');
  });

  it('creates parent directories as needed', () => {
    writeVisionMarkdown(makeVision(), 'deeply/nested/v.md', cwd);
    expect(existsSync(join(cwd, 'deeply', 'nested', 'v.md'))).toBe(true);
  });

  it('honors absolute paths verbatim', () => {
    const abs = join(cwd, 'absolute.md');
    const path = writeVisionMarkdown(makeVision(), abs, cwd);
    expect(path).toBe(abs);
    expect(existsSync(abs)).toBe(true);
  });
});
