// SLOPE CodexAdapter — adapts guard framework to OpenAI Codex CLI's hook system.
// Codex hooks use the same JSON stdin/stdout protocol as Claude Code.
// Hooks config: .codex/hooks.json | MCP config: .codex/config.toml
// Project instructions: AGENTS.md (auto-generated by slope init)

import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { HarnessAdapter, ToolNameMap } from '../harness.js';
import { registerAdapter, SLOPE_BIN_PREAMBLE, writeOrUpdateManagedScript } from '../harness.js';
import type { GuardResult, AnyGuardDefinition, PreToolUseOutput, PostToolUseOutput, StopOutput, Suggestion } from '../guard.js';

// Codex CLI uses similar tool names to Claude Code
const CODEX_TOOLS: ToolNameMap = {
  read_file: 'Read',
  write_file: 'Edit|Write',
  search_files: 'Glob',
  search_content: 'Grep',
  execute_command: 'Bash',
  create_subagent: 'Agent',
  exit_plan: 'ExitPlanMode',
  enter_worktree: 'EnterWorktree',
};

export class CodexAdapter implements HarnessAdapter {
  readonly id = 'codex' as const;
  readonly displayName = 'Codex CLI';
  readonly toolNames: ToolNameMap = CODEX_TOOLS;
  // Codex supports PreToolUse + PostToolUse (Bash only currently) + Stop
  // PreCompact not supported
  readonly supportedEvents = new Set(['PreToolUse', 'PostToolUse', 'Stop']);
  readonly supportsContextInjection = true;

  hooksConfigPath(cwd: string): string | null {
    return join(cwd, '.codex', 'hooks.json');
  }

  detect(cwd: string): boolean {
    return existsSync(join(cwd, '.codex')) || existsSync(join(cwd, '.codex', 'config.toml'));
  }

  formatSuggestion(suggestion: Suggestion): string {
    const lines: string[] = [`SLOPE ${suggestion.title}: ${suggestion.context}`];
    if (suggestion.options.length > 0) {
      lines.push('', 'Options:');
      for (let i = 0; i < suggestion.options.length; i++) {
        const opt = suggestion.options[i];
        const desc = opt.description ? ` — ${opt.description}` : '';
        lines.push(`${i + 1}. ${opt.label}${desc}`);
      }
    }
    return lines.join('\n');
  }

  formatPreToolOutput(result: GuardResult): PreToolUseOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    const context = [result.context, suggestionText].filter(Boolean).join('\n\n') || undefined;
    const blockReason = result.blockReason ?? (
      result.suggestion?.requiresDecision && result.suggestion.priority === 'critical'
        ? suggestionText : undefined
    );

    return {
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        ...(result.decision && { permissionDecision: result.decision }),
        ...(blockReason && { permissionDecision: 'deny', permissionDecisionReason: blockReason }),
        ...(context && { additionalContext: context }),
      },
    };
  }

  formatPostToolOutput(result: GuardResult): PostToolUseOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    if (result.blockReason) {
      return {
        decision: 'block',
        reason: result.blockReason,
      };
    }
    const context = [result.context, suggestionText].filter(Boolean).join('\n\n') || undefined;
    if (context) {
      return {
        hookSpecificOutput: {
          hookEventName: 'PostToolUse',
          additionalContext: context,
        },
      };
    }
    return {};
  }

  formatStopOutput(result: GuardResult): StopOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    const effectiveBlockReason = result.blockReason ?? (
      result.suggestion?.requiresDecision ? suggestionText : undefined
    );
    if (effectiveBlockReason) {
      return { decision: 'block', reason: effectiveBlockReason };
    }
    return {};
  }

  generateHooksConfig(
    guards: AnyGuardDefinition[],
    guardScriptPath: string,
  ): Record<string, Array<{ matcher?: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>> {
    const config: Record<string, Array<{ matcher?: string; hooks: Array<{ type: string; command: string; timeout?: number }> }>> = {};

    for (const guard of guards) {
      const event = guard.hookEvent;
      if (!this.supportedEvents.has(event)) continue;

      if (!config[event]) config[event] = [];

      const entry: { matcher?: string; hooks: Array<{ type: string; command: string; timeout?: number }> } = {
        hooks: [{
          type: 'command',
          command: `"${guardScriptPath}" ${guard.name}`,
          timeout: 10,
        }],
      };

      if (guard.matcher) entry.matcher = guard.matcher;
      config[event].push(entry);
    }

    return config;
  }

  installGuards(cwd: string, guards: AnyGuardDefinition[]): void {
    const hooksDir = join(cwd, '.codex', 'hooks');
    mkdirSync(hooksDir, { recursive: true });

    // Write guard dispatcher script
    const scriptPath = join(hooksDir, 'slope-guard.sh');
    writeOrUpdateManagedScript(scriptPath, [
      SLOPE_BIN_PREAMBLE,
      'slope guard "$@"',
    ].join('\n'));

    // Write hooks.json
    const hooksConfig = this.generateHooksConfig(guards, scriptPath);
    const configPath = join(cwd, '.codex', 'hooks.json');

    let existing: Record<string, unknown> = {};
    if (existsSync(configPath)) {
      try { existing = JSON.parse(readFileSync(configPath, 'utf8')); } catch { /* start fresh */ }
    }

    // Merge SLOPE hooks into existing config
    for (const [event, entries] of Object.entries(hooksConfig)) {
      if (!existing[event]) existing[event] = [];
      const existingEntries = existing[event] as unknown[];
      existingEntries.push(...entries);
    }

    writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n');
  }
}

// Auto-register on import
registerAdapter(new CodexAdapter());
