// SLOPE CodexAdapter — adapts guard framework to OpenAI Codex CLI's hook system.
// Codex hooks use the same JSON stdin/stdout protocol as Claude Code.
// Hooks config: .codex/hooks.json | MCP config: .codex/config.toml
// Project instructions: AGENTS.md (auto-generated by slope init)

import { existsSync, writeFileSync, readFileSync, mkdirSync, chmodSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { HarnessAdapter, HarnessInstallOptions, ToolNameMap } from '../harness.js';
import { registerAdapter, resolveToolMatcher } from '../harness.js';
import type { GuardResult, AnyGuardDefinition, PreToolUseOutput, PostToolUseOutput, StopOutput, Suggestion } from '../guard.js';

type CodexHookHandler = { type: string; command: string; timeout?: number; statusMessage?: string };
type CodexHookGroup = { matcher?: string; hooks: CodexHookHandler[] };
type CodexHooksByEvent = Record<string, CodexHookGroup[]>;
type CodexHooksFile = { hooks: CodexHooksByEvent } & Record<string, unknown>;

// Codex currently emits tool hooks for Bash, apply_patch, and MCP tools.
// Edit/Write are accepted matcher aliases for apply_patch.
const CODEX_TOOLS: ToolNameMap = {
  read_file: 'mcp__.*__read.*',
  write_file: 'apply_patch|Edit|Write',
  search_files: 'mcp__.*__glob.*|mcp__.*__list.*|mcp__.*__search.*',
  search_content: 'mcp__.*__grep.*|mcp__.*__search.*',
  execute_command: 'Bash',
  create_subagent: 'Agent',
  exit_plan: 'ExitPlanMode',
  enter_worktree: 'EnterWorktree',
};

const MANAGED_START = '# === SLOPE MANAGED (do not edit above this line) ===';
const MANAGED_END = '# === SLOPE END ===';

export class CodexAdapter implements HarnessAdapter {
  readonly id = 'codex' as const;
  readonly displayName = 'Codex CLI';
  readonly toolNames: ToolNameMap = CODEX_TOOLS;
  // Codex supports PreToolUse + PostToolUse (Bash only currently) + Stop
  // PreCompact not supported
  readonly supportedEvents = new Set(['PreToolUse', 'PostToolUse', 'Stop']);
  readonly supportsContextInjection = true;

  hooksConfigPath(cwd: string): string | null {
    return join(cwd, '.codex', 'hooks.json');
  }

  detect(cwd: string): boolean {
    return existsSync(join(cwd, '.codex')) || existsSync(join(cwd, '.codex', 'config.toml'));
  }

  formatSuggestion(suggestion: Suggestion): string {
    const lines: string[] = [`SLOPE ${suggestion.title}: ${suggestion.context}`];
    if (suggestion.options.length > 0) {
      lines.push('', 'Options:');
      for (let i = 0; i < suggestion.options.length; i++) {
        const opt = suggestion.options[i];
        const desc = opt.description ? ` — ${opt.description}` : '';
        lines.push(`${i + 1}. ${opt.label}${desc}`);
      }
    }
    return lines.join('\n');
  }

  formatPreToolOutput(result: GuardResult): PreToolUseOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    const context = [result.context, suggestionText].filter(Boolean).join('\n\n') || undefined;
    const blockReason = result.blockReason ?? (
      result.suggestion?.requiresDecision && result.suggestion.priority === 'critical'
        ? suggestionText : undefined
    );

    return {
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        ...(result.decision && { permissionDecision: result.decision }),
        ...(blockReason && { permissionDecision: 'deny', permissionDecisionReason: blockReason }),
        ...(context && { additionalContext: context }),
      },
    };
  }

  formatPostToolOutput(result: GuardResult): PostToolUseOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    if (result.blockReason) {
      return {
        decision: 'block',
        reason: result.blockReason,
      };
    }
    const context = [result.context, suggestionText].filter(Boolean).join('\n\n') || undefined;
    if (context) {
      return {
        hookSpecificOutput: {
          hookEventName: 'PostToolUse',
          additionalContext: context,
        },
      };
    }
    return {};
  }

  formatStopOutput(result: GuardResult): StopOutput {
    const suggestionText = result.suggestion && !result.blockReason
      ? this.formatSuggestion(result.suggestion) : undefined;
    const effectiveBlockReason = result.blockReason ?? (
      result.suggestion?.requiresDecision ? suggestionText : undefined
    );
    if (effectiveBlockReason) {
      return { decision: 'block', reason: effectiveBlockReason };
    }
    return {};
  }

  generateHooksConfig(
    guards: AnyGuardDefinition[],
    guardScriptPath: string,
  ): CodexHooksFile {
    const hooks: CodexHooksByEvent = {};
    const byEventAndMatcher = new Map<string, { event: string; matcher?: string; guards: AnyGuardDefinition[] }>();

    for (const guard of guards) {
      const event = guard.hookEvent;
      if (!this.supportedEvents.has(event)) continue;
      const matcher = resolveToolMatcher(this, 'toolCategories' in guard ? guard.toolCategories : undefined) ?? guard.matcher;
      const key = `${event}\0${matcher ?? ''}`;
      const group = byEventAndMatcher.get(key) ?? { event, matcher, guards: [] };
      group.guards.push(guard);
      byEventAndMatcher.set(key, group);
    }

    for (const group of byEventAndMatcher.values()) {
      if (!hooks[group.event]) hooks[group.event] = [];

      const entry: CodexHookGroup = {
        hooks: group.guards.map(guard => ({
          type: 'command',
          command: formatCodexGuardCommand(guardScriptPath, guard.name),
          timeout: 10,
          statusMessage: `SLOPE ${guard.name}`,
        })),
      };

      if (group.matcher) entry.matcher = group.matcher;
      hooks[group.event].push(entry);
    }

    return { hooks };
  }

  installGuards(cwd: string, guards: AnyGuardDefinition[], options: HarnessInstallOptions = {}): void {
    const rootDir = options.scope === 'user'
      ? join(options.homeDir ?? homedir(), '.codex')
      : join(cwd, '.codex');
    const hooksDir = join(rootDir, 'hooks');
    mkdirSync(hooksDir, { recursive: true });

    const scriptPath = join(hooksDir, 'slope-guard.sh');
    writeCodexGuardDispatcher(scriptPath, options.scope === 'user');

    const hooksConfig = this.generateHooksConfig(guards, scriptPath);
    const configPath = join(rootDir, 'hooks.json');
    writeCodexHooksConfig(configPath, hooksConfig, scriptPath);
  }
}

function formatCodexGuardCommand(scriptPath: string, guardName: string): string {
  return `"${scriptPath}" ${guardName}`;
}

function writeCodexGuardDispatcher(scriptPath: string, userLevel: boolean): void {
  const body = userLevel
    ? [
        'SLOPE_PROJECT_DIR="${CODEX_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"',
        '',
        'if [ ! -d "$SLOPE_PROJECT_DIR/.slope" ]; then',
        '  exit 0',
        'fi',
        '',
        'if [ -x "$SLOPE_PROJECT_DIR/node_modules/.bin/slope" ]; then',
        '  SLOPE_BIN="$SLOPE_PROJECT_DIR/node_modules/.bin/slope"',
        'elif [ -f "$SLOPE_PROJECT_DIR/dist/cli/index.js" ] && [ -f "$SLOPE_PROJECT_DIR/package.json" ] && grep -q \'"name": "@slope-dev/slope"\' "$SLOPE_PROJECT_DIR/package.json"; then',
        '  exec node "$SLOPE_PROJECT_DIR/dist/cli/index.js" guard "$@"',
        'elif command -v slope >/dev/null 2>&1; then',
        '  SLOPE_BIN="$(command -v slope)"',
        'else',
        '  exit 0',
        'fi',
        '',
        'cd "$SLOPE_PROJECT_DIR"',
        'exec "$SLOPE_BIN" guard "$@"',
      ]
    : [
        'SLOPE_PROJECT_DIR="${CODEX_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"',
        '',
        'if [ -x "$SLOPE_PROJECT_DIR/node_modules/.bin/slope" ]; then',
        '  SLOPE_BIN="$SLOPE_PROJECT_DIR/node_modules/.bin/slope"',
        'elif [ -f "$SLOPE_PROJECT_DIR/dist/cli/index.js" ] && [ -f "$SLOPE_PROJECT_DIR/package.json" ] && grep -q \'"name": "@slope-dev/slope"\' "$SLOPE_PROJECT_DIR/package.json"; then',
        '  exec node "$SLOPE_PROJECT_DIR/dist/cli/index.js" guard "$@"',
        'elif command -v slope >/dev/null 2>&1; then',
        '  SLOPE_BIN="$(command -v slope)"',
        'else',
        '  SLOPE_BIN="npx --yes @slope-dev/slope"',
        'fi',
        '',
        'cd "$SLOPE_PROJECT_DIR"',
        'exec "$SLOPE_BIN" guard "$@"',
      ];
  const script = [
    '#!/usr/bin/env bash',
    '# SLOPE Codex guard dispatcher.',
    '',
    'set -euo pipefail',
    '',
    MANAGED_START,
    ...body,
    MANAGED_END,
    '',
  ].join('\n');

  if (existsSync(scriptPath)) {
    const existing = readFileSync(scriptPath, 'utf8');
    const startIdx = existing.indexOf(MANAGED_START);
    const endIdx = existing.indexOf(MANAGED_END);
    if (startIdx !== -1 && endIdx !== -1) {
      const nextManaged = script.slice(script.indexOf(MANAGED_START) + MANAGED_START.length, script.indexOf(MANAGED_END));
      const updated = existing.slice(0, startIdx + MANAGED_START.length) + nextManaged + existing.slice(endIdx);
      writeFileSync(scriptPath, updated);
      chmodSync(scriptPath, 0o755);
      return;
    }
    if (!isSlopeGeneratedDispatcher(existing)) return;
  }

  writeFileSync(scriptPath, script, { mode: 0o755 });
}

function isSlopeGeneratedDispatcher(content: string): boolean {
  return content.includes('slope guard "$@"') || content.includes('guard "$@"');
}

function writeCodexHooksConfig(configPath: string, hooksConfig: CodexHooksFile, scriptPath: string): void {
  let existing: CodexHooksFile = { hooks: {} };
  if (existsSync(configPath)) {
    try {
      const parsed = JSON.parse(readFileSync(configPath, 'utf8')) as Record<string, unknown>;
      existing = {
        ...parsed,
        hooks: isHooksByEvent(parsed.hooks) ? parsed.hooks : {},
      };
    } catch { /* start fresh */ }
  }

  for (const [event, entries] of Object.entries(hooksConfig.hooks)) {
    const existingEntries = existing.hooks[event] ?? [];
    const withoutManagedSlope = existingEntries.filter(entry =>
      !entry.hooks.some(hook => hook.command.includes(scriptPath)),
    );
    existing.hooks[event] = [...withoutManagedSlope, ...entries];
  }

  writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n');
}

function isHooksByEvent(value: unknown): value is CodexHooksByEvent {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  return Object.values(value).every(groups =>
    Array.isArray(groups) && groups.every(group =>
      group && typeof group === 'object' && Array.isArray((group as CodexHookGroup).hooks),
    ),
  );
}

// Auto-register on import
registerAdapter(new CodexAdapter());
