// SLOPE GenericAdapter — fallback adapter for any harness without a dedicated adapter.
// Outputs simple JSON, generates a guards manifest, and creates shell-based dispatcher.

import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { HarnessAdapter, ToolNameMap } from '../harness.js';
import { registerAdapter, resolveToolMatcher, SLOPE_BIN_PREAMBLE } from '../harness.js';
import type { GuardResult, AnyGuardDefinition } from '../guard.js';

/** Generic tool name map — uses common operation names */
const GENERIC_TOOLS: ToolNameMap = {
  read_file: 'read_file',
  write_file: 'write_file',
  search_files: 'search_files',
  search_content: 'search_content',
  execute_command: 'execute_command',
  create_subagent: 'create_subagent',
  exit_plan: 'exit_plan',
};

/** Guard manifest entry written to guards-manifest.json */
export interface GuardManifestEntry {
  name: string;
  description: string;
  hookEvent: string;
  matcher?: string;
  level: string;
  command: string;
}

/** Generic adapter — works with any harness via shell scripts and JSON manifest. */
export class GenericAdapter implements HarnessAdapter {
  readonly id = 'generic' as const;
  readonly displayName = 'Generic (Shell)';
  readonly toolNames: ToolNameMap = GENERIC_TOOLS;
  readonly supportedEvents = new Set(['PreToolUse', 'PostToolUse', 'Stop']);
  readonly supportsContextInjection = false;

  hooksConfigPath(_cwd: string): string | null {
    return null;
  }

  formatPreToolOutput(result: GuardResult): unknown {
    const action = result.decision === 'deny' ? 'deny'
      : result.decision === 'ask' ? 'ask'
      : result.context ? 'context'
      : 'allow';
    return {
      action,
      ...(result.context && { message: result.context }),
      ...(result.blockReason && { reason: result.blockReason }),
    };
  }

  formatPostToolOutput(result: GuardResult): unknown {
    return {
      action: result.blockReason ? 'deny' : result.context ? 'context' : 'allow',
      ...(result.context && { message: result.context }),
      ...(result.blockReason && { reason: result.blockReason }),
    };
  }

  formatStopOutput(result: GuardResult): unknown {
    return {
      action: result.blockReason ? 'deny' : 'allow',
      ...(result.blockReason && { reason: result.blockReason }),
    };
  }

  generateHooksConfig(guards: AnyGuardDefinition[], guardScriptPath: string): GuardManifestEntry[] {
    return guards.map(g => {
      // Resolve matcher via toolCategories (harness-agnostic) with fallback to raw matcher
      const matcher = resolveToolMatcher(this, 'toolCategories' in g ? g.toolCategories : undefined) ?? g.matcher;
      return {
        name: g.name,
        description: g.description,
        hookEvent: g.hookEvent,
        ...(matcher && { matcher }),
        level: g.level,
        command: `${guardScriptPath} ${g.name}`,
      };
    });
  }

  installGuards(cwd: string, guards: AnyGuardDefinition[]): void {
    const hooksDir = join(cwd, '.slope', 'hooks');
    mkdirSync(hooksDir, { recursive: true });

    // Create the guard dispatcher script
    const dispatcherPath = join(hooksDir, 'slope-guard.sh');
    if (!existsSync(dispatcherPath)) {
      const script = [
        '#!/usr/bin/env bash',
        '# SLOPE guard dispatcher — routes hook events to slope guard handlers',
        '# Auto-generated by slope hook add --level=full --harness=generic',
        '#',
        '# Usage: ./slope-guard.sh <guard-name>',
        '# Reads JSON from stdin, outputs JSON to stdout.',
        '# See guards-manifest.json for available guards.',
        '',
        '# === SLOPE MANAGED (do not edit above this line) ===',
        ...SLOPE_BIN_PREAMBLE,
        '',
        'slope guard "$@"',
        '# === SLOPE END ===',
        '',
      ].join('\n');
      writeFileSync(dispatcherPath, script, { mode: 0o755 });
      console.log(`  Created ${dispatcherPath}`);
    }

    // Generate guards manifest
    const manifestPath = join(hooksDir, 'guards-manifest.json');
    const manifest = this.generateHooksConfig(guards, './slope-guard.sh');
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
    console.log(`  Created ${manifestPath}`);

    // Generate README
    const readmePath = join(hooksDir, 'README.md');
    if (!existsSync(readmePath)) {
      const readme = [
        '# SLOPE Guard Hooks',
        '',
        'This directory contains SLOPE guard hooks for use with any AI coding harness.',
        '',
        '## Files',
        '',
        '- `slope-guard.sh` — Dispatcher script that routes guard names to `slope guard`',
        '- `guards-manifest.json` — Machine-readable list of all installed guards',
        '',
        '## Integration',
        '',
        'To wire these guards into your harness:',
        '',
        '1. Configure your harness to call `slope-guard.sh <guard-name>` at the appropriate hook event',
        '2. Pass the hook context as JSON on stdin',
        '3. Read the JSON response from stdout',
        '',
        '### Hook Events',
        '',
        '- **PreToolUse** — Before a tool executes (can allow, deny, or inject context)',
        '- **PostToolUse** — After a tool executes (can block or inject context)',
        '- **Stop** — Before session ends (can block to prevent premature exit)',
        '- **PreCompact** — Before context compaction (extract state before compression)',
        '',
        '### Response Format',
        '',
        '```json',
        '{ "action": "allow" | "deny" | "context", "message": "...", "reason": "..." }',
        '```',
        '',
        'See `guards-manifest.json` for the full list of guards and their hook events.',
        '',
      ].join('\n');
      writeFileSync(readmePath, readme);
      console.log(`  Created ${readmePath}`);
    }
  }

  detect(_cwd: string): boolean {
    // Generic is the fallback — only used when no other adapter matches
    return true;
  }
}

/** Singleton instance */
export const genericAdapter = new GenericAdapter();

// Auto-register on import
registerAdapter(genericAdapter);
