// SLOPE WindsurfAdapter — adapts guard framework to Windsurf's Cascade hook system.
// Windsurf uses exit-code-based blocking: 0 = allow, 2 = block.
// The adapter itself is JSON-in/JSON-out; the dispatcher script translates to exit codes.
//
// Limitation: Windsurf cannot inject additionalContext into the agent's context.
// Guards can block but not add guidance. No on-stop event support.

import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { HarnessAdapter, ToolNameMap } from '../harness.js';
import { registerAdapter, resolveToolMatcher } from '../harness.js';
import type { GuardResult, AnyGuardDefinition } from '../guard.js';

/** Windsurf tool name mappings */
const WINDSURF_TOOLS: ToolNameMap = {
  read_file: 'read_file',
  write_file: 'create_file|edit_file',
  search_files: 'find_files',
  search_content: 'search',
  execute_command: 'run_command',
  create_subagent: 'create_subagent',
  exit_plan: 'exit_plan',
};

/** Windsurf hook entry in .windsurf/hooks.json */
export interface WindsurfHookEntry {
  event: string;
  matcher?: string;
  command: string;
  timeout?: number;
  description?: string;
}

/** Windsurf hooks config shape */
export interface WindsurfHooksConfig {
  hooks: WindsurfHookEntry[];
}

/** Windsurf hook output (JSON from adapter, translated to exit codes by dispatcher) */
export interface WindsurfHookOutput {
  action: 'allow' | 'deny';
  message?: string;
}

/**
 * Map SLOPE hook events to Windsurf hook events.
 * Stop is intentionally omitted — Windsurf has no session-end hook.
 * PreCompact is intentionally omitted — Windsurf has no pre-compaction hook.
 */
const HOOK_EVENT_MAP: Partial<Record<'PreToolUse' | 'PostToolUse' | 'Stop' | 'PreCompact', string>> = {
  PreToolUse: 'pre-tool-use',
  PostToolUse: 'post-tool-use',
};

/** Windsurf adapter — formats guard output for Windsurf's exit-code-based hook system. */
export class WindsurfAdapter implements HarnessAdapter {
  readonly id = 'windsurf' as const;
  readonly displayName = 'Windsurf';
  readonly toolNames: ToolNameMap = WINDSURF_TOOLS;
  readonly supportedEvents = new Set(['PreToolUse', 'PostToolUse']);
  readonly supportsContextInjection = false;

  hooksConfigPath(cwd: string): string | null {
    return join(cwd, '.windsurf', 'hooks.json');
  }

  formatPreToolOutput(result: GuardResult): WindsurfHookOutput {
    if (result.decision === 'deny' || result.blockReason) {
      return {
        action: 'deny',
        ...(result.blockReason && { message: result.blockReason }),
      };
    }
    // 'ask' and context-only fall through to 'allow' — Windsurf can't inject context or prompt
    return { action: 'allow' };
  }

  formatPostToolOutput(result: GuardResult): WindsurfHookOutput {
    if (result.blockReason) {
      return {
        action: 'deny',
        message: result.blockReason,
      };
    }
    return { action: 'allow' };
  }

  formatStopOutput(result: GuardResult): WindsurfHookOutput {
    // Windsurf doesn't support stop hooks, but format consistently
    if (result.blockReason) {
      return {
        action: 'deny',
        message: result.blockReason,
      };
    }
    return { action: 'allow' };
  }

  generateHooksConfig(guards: AnyGuardDefinition[], guardScriptPath: string): WindsurfHooksConfig {
    const hooks: WindsurfHookEntry[] = [];

    for (const g of guards) {
      const windsurfEvent = HOOK_EVENT_MAP[g.hookEvent];
      if (!windsurfEvent) continue; // Skip unsupported hook events (e.g., Stop)

      const matcher = resolveToolMatcher(this, 'toolCategories' in g ? g.toolCategories : undefined) ?? g.matcher;

      const entry: WindsurfHookEntry = {
        event: windsurfEvent,
        command: `${guardScriptPath} ${g.name}`,
        timeout: 10000,
        description: `SLOPE: ${g.description}`,
      };
      if (matcher) entry.matcher = matcher;
      hooks.push(entry);
    }

    return { hooks };
  }

  installGuards(cwd: string, guards: AnyGuardDefinition[]): void {
    const hooksDir = join(cwd, '.windsurf', 'hooks');
    mkdirSync(hooksDir, { recursive: true });

    // Create the exit-code dispatcher script
    // This wraps `slope guard`, reads JSON output, and translates to exit codes
    const dispatcherPath = join(hooksDir, 'slope-guard.sh');
    if (!existsSync(dispatcherPath)) {
      const script = [
        '#!/usr/bin/env bash',
        '# SLOPE guard dispatcher for Windsurf — translates JSON to exit codes',
        '# Auto-generated by slope hook add --level=full --harness=windsurf',
        '#',
        '# Windsurf exit-code protocol:',
        '#   exit 0 = allow (tool proceeds)',
        '#   exit 2 = block (tool denied)',
        '#   other  = error (logged, tool proceeds)',
        '',
        '# === SLOPE MANAGED (do not edit above this line) ===',
        'OUTPUT=$(slope guard "$@" 2>"${SLOPE_GUARD_LOG:-/dev/null}")',
        'if [ $? -ne 0 ]; then',
        '  exit 0  # Guard errored — allow tool to proceed',
        'fi',
        '# Parse action from JSON (handles both compact and prettified output)',
        'ACTION=$(echo "$OUTPUT" | grep -o \'"action"[[:space:]]*:[[:space:]]*"[^"]*"\' | head -1 | cut -d\'"\' -f4)',
        '',
        'if [ "$ACTION" = "deny" ]; then',
        '  exit 2',
        'fi',
        'exit 0',
        '# === SLOPE END ===',
        '',
      ].join('\n');
      writeFileSync(dispatcherPath, script, { mode: 0o755 });
      console.log(`  Created ${dispatcherPath}`);
    }

    // Generate hooks config and merge into .windsurf/hooks.json
    const guardScript = '.windsurf/hooks/slope-guard.sh';
    const hooksConfig = this.generateHooksConfig(guards, guardScript);

    const configPath = join(cwd, '.windsurf', 'hooks.json');
    let existing: WindsurfHooksConfig = { hooks: [] };
    if (existsSync(configPath)) {
      try {
        existing = JSON.parse(readFileSync(configPath, 'utf8'));
        if (!Array.isArray(existing.hooks)) existing.hooks = [];
      } catch { /* start fresh */ }
    }

    // Merge — avoid duplicates by checking command + event
    for (const entry of hooksConfig.hooks) {
      const isDuplicate = existing.hooks.some(
        e => e.command === entry.command && e.event === entry.event,
      );
      if (!isDuplicate) {
        existing.hooks.push(entry);
      }
    }

    writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n');
    console.log(`  Updated ${configPath} with guard hooks`);

    // Generate guards manifest for reference
    const manifestPath = join(hooksDir, 'guards-manifest.json');
    const manifest = guards
      .filter(g => HOOK_EVENT_MAP[g.hookEvent])
      .map(g => {
        const matcher = resolveToolMatcher(this, 'toolCategories' in g ? g.toolCategories : undefined) ?? g.matcher;
        return {
          name: g.name,
          description: g.description,
          hookEvent: g.hookEvent,
          ...(matcher && { matcher }),
          level: g.level,
          command: `${guardScript} ${g.name}`,
        };
      });
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
    console.log(`  Created ${manifestPath}`);
  }

  detect(cwd: string): boolean {
    return existsSync(join(cwd, '.windsurf'));
  }
}

/** Singleton instance */
export const windsurfAdapter = new WindsurfAdapter();

// Auto-register on import
registerAdapter(windsurfAdapter);
