// SLOPE Plugin for OpenCode
// Auto-generated by `slope init --opencode`
// Logs session lifecycle events to SLOPE's SQLite store.

export default async ({ $ }) => {
  return {
    event: async ({ event }) => {
      switch (event.type) {
        case 'session.created':
          await $`slope session start --ide=opencode --role=primary`;
          await $`slope briefing --compact`;
          break;

        case 'session.idle':
        case 'session.deleted':
          if (process.env.SLOPE_SESSION_ID) {
            await $`slope session end --session-id=${process.env.SLOPE_SESSION_ID}`;
          }
          break;

        case 'session.compacted':
          if (process.env.SLOPE_SESSION_ID) {
            await $`slope session heartbeat --session-id=${process.env.SLOPE_SESSION_ID}`;
          }
          break;
      }
    },
  };
};
