// SLOPE — Vision Document: project intent and direction
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, resolve, relative, isAbsolute as pathIsAbsolute } from 'node:path';
import type { VisionDocument } from './analyzers/types.js';

const DEFAULT_VISION_PATH = '.slope/vision.json';

export function loadVision(cwd?: string): VisionDocument | null {
  const root = cwd ?? process.cwd();
  const filePath = join(root, DEFAULT_VISION_PATH);
  if (!existsSync(filePath)) return null;
  try {
    return JSON.parse(readFileSync(filePath, 'utf8')) as VisionDocument;
  } catch {
    return null;
  }
}

export function saveVision(vision: VisionDocument, cwd?: string): void {
  const root = cwd ?? process.cwd();
  const filePath = join(root, DEFAULT_VISION_PATH);
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(filePath, JSON.stringify(vision, null, 2) + '\n');
}

/** Render the vision as a tracked Markdown document.
 *  Output is intended to live alongside the project (e.g. docs/vision.md)
 *  so collaborators and agents have a tracked source of truth — see GH #305. */
export function renderVisionMarkdown(vision: VisionDocument): string {
  const lines: string[] = [];
  lines.push('# Project Vision');
  lines.push('');
  lines.push('<!-- Generated by `slope vision create --write-md` (or `--update --write-md`). -->');
  lines.push('<!-- Canonical data lives at .slope/vision.json — regenerate this file on changes. -->');
  lines.push('');
  lines.push('## Purpose');
  lines.push('');
  lines.push(vision.purpose);
  lines.push('');

  if (vision.audience) {
    lines.push('## Audience');
    lines.push('');
    lines.push(vision.audience);
    lines.push('');
  }

  if (vision.priorities && vision.priorities.length > 0) {
    lines.push('## Priorities');
    lines.push('');
    for (const p of vision.priorities) lines.push(`- ${p}`);
    lines.push('');
  }

  if (vision.techDirection) {
    lines.push('## Technical direction');
    lines.push('');
    lines.push(vision.techDirection);
    lines.push('');
  }

  if (vision.nonGoals && vision.nonGoals.length > 0) {
    lines.push('## Non-goals');
    lines.push('');
    for (const ng of vision.nonGoals) lines.push(`- ${ng}`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`_Updated ${vision.updatedAt}_`);
  lines.push('');
  return lines.join('\n');
}

/** Write the vision to a Markdown file at the given cwd-relative path.
 *  Creates parent directories as needed. Refuses paths that resolve outside
 *  the project root (absolute paths or `..` traversal) unless
 *  SLOPE_VISION_MD_ALLOW_ABS=1 is set — guards against accidental
 *  /etc/passwd-style escapes via --write-md=<path>. */
export function writeVisionMarkdown(vision: VisionDocument, mdPath: string, cwd?: string): string {
  const root = cwd ?? process.cwd();
  const allowAbsolute = process.env.SLOPE_VISION_MD_ALLOW_ABS === '1';
  const abs = pathIsAbsolute(mdPath) ? resolve(mdPath) : resolve(root, mdPath);

  // Containment check — refuse paths outside the project root.
  const rootResolved = resolve(root);
  const rel = relative(rootResolved, abs);
  if (!allowAbsolute && rel && (rel.startsWith('..') || pathIsAbsolute(rel))) {
    throw new Error(
      `writeVisionMarkdown: refusing to write outside project root (${root}). ` +
      `Path "${mdPath}" resolves to "${abs}". Set SLOPE_VISION_MD_ALLOW_ABS=1 to override.`,
    );
  }

  const dir = dirname(abs);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(abs, renderVisionMarkdown(vision));
  return abs;
}

/** Create a new vision document with timestamps. Validates, saves, and returns it. */
export function createVision(fields: {
  purpose: string;
  priorities: string[];
  audience?: string;
  techDirection?: string;
  nonGoals?: string[];
}, cwd?: string): VisionDocument {
  const existing = loadVision(cwd);
  if (existing) throw new Error('Vision already exists. Use updateVision() to modify it.');
  const now = new Date().toISOString();
  const vision: VisionDocument = {
    purpose: fields.purpose,
    priorities: fields.priorities,
    audience: fields.audience,
    techDirection: fields.techDirection,
    nonGoals: fields.nonGoals,
    createdAt: now,
    updatedAt: now,
  };
  const errors = validateVision(vision);
  if (errors.length > 0) throw new Error(`Invalid vision: ${errors.join(', ')}`);
  saveVision(vision, cwd);
  return vision;
}

/** Update fields of an existing vision document. Preserves createdAt, bumps updatedAt. */
export function updateVision(fields: Partial<Omit<VisionDocument, 'createdAt' | 'updatedAt'>>, cwd?: string): VisionDocument {
  const existing = loadVision(cwd);
  if (!existing) throw new Error('No vision exists. Use createVision() first.');
  const updated: VisionDocument = {
    ...existing,
    ...Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== undefined)),
    updatedAt: new Date().toISOString(),
  };
  const errors = validateVision(updated);
  if (errors.length > 0) throw new Error(`Invalid vision: ${errors.join(', ')}`);
  saveVision(updated, cwd);
  return updated;
}

export function validateVision(vision: unknown): string[] {
  const errors: string[] = [];

  if (!vision || typeof vision !== 'object') {
    errors.push('Vision must be an object');
    return errors;
  }

  const v = vision as Record<string, unknown>;

  if (!v.purpose || typeof v.purpose !== 'string' || v.purpose.trim() === '') {
    errors.push('purpose is required and must be a non-empty string');
  }

  if (!Array.isArray(v.priorities)) {
    errors.push('priorities must be an array');
  } else {
    for (let i = 0; i < v.priorities.length; i++) {
      if (typeof v.priorities[i] !== 'string') {
        errors.push(`priorities[${i}] must be a string`);
      }
    }
  }

  if (v.createdAt !== undefined && typeof v.createdAt === 'string') {
    if (isNaN(Date.parse(v.createdAt))) {
      errors.push('createdAt must be a valid ISO date string');
    }
  }

  if (v.updatedAt !== undefined && typeof v.updatedAt === 'string') {
    if (isNaN(Date.parse(v.updatedAt))) {
      errors.push('updatedAt must be a valid ISO date string');
    }
  }

  return errors;
}
