import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { compareSprintIdKeys, formatSprintReview, normalizeScorecard, sprintIdKey, sprintIdsEqual } from '../../core/index.js';
import type { GolfScorecard } from '../../core/index.js';
import { loadConfig } from '../config.js';
import { resolveMetaphor } from '../metaphor.js';
import { loadSprintState, updateGate } from '../sprint-state.js';

function discoverScorecardPaths(cwd: string, config: ReturnType<typeof loadConfig>): string[] {
  const dir = join(cwd, config.scorecardDir);
  if (!existsSync(dir)) return [];
  const patternParts = config.scorecardPattern.split('*');
  const prefix = patternParts[0] ?? '';
  const suffix = patternParts[1] ?? '';
  const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`^${escapeRegex(prefix)}(\\d+(?:\\.\\d+)?)${escapeRegex(suffix)}$`);

  return readdirSync(dir)
    .map(file => ({ file, sprint: sprintIdKey(file.match(regex)?.[1] ?? '') }))
    .filter((entry): entry is { file: string; sprint: string } =>
      entry.sprint != null && compareSprintIdKeys(entry.sprint, String(config.minSprint)) >= 0,
    )
    .sort((a, b) => compareSprintIdKeys(a.sprint, b.sprint))
    .map(entry => join(dir, entry.file));
}

function resolveScorecardPath(
  path: string | undefined,
  sprintSelector: string | undefined,
  cwd: string,
  config: ReturnType<typeof loadConfig>,
): string {
  if (path && sprintSelector) {
    console.error('\nUse either an explicit scorecard path or --sprint, not both.\n');
    process.exit(1);
  }
  if (path) return isAbsolute(path) ? path : resolve(cwd, path);

  if (sprintSelector) {
    const sprint = sprintIdKey(sprintSelector);
    if (sprint == null) {
      console.error(`\nInvalid sprint selector: ${sprintSelector}\n`);
      process.exit(1);
    }
    const selected = join(cwd, config.scorecardDir, config.scorecardPattern.replace('*', String(sprint)));
    if (!existsSync(selected)) {
      console.error(`\nScorecard not found for Sprint ${sprint}: ${relative(cwd, selected)}\n`);
      process.exit(1);
    }
    return selected;
  }

  const scorecards = discoverScorecardPaths(cwd, config);
  if (scorecards.length === 0) {
    console.error('\nNo scorecards found. Pass an explicit scorecard path.\n');
    process.exit(1);
  }
  if (scorecards.length > 1) {
    console.error('\nMultiple scorecards found; refusing to guess which sprint to review.');
    console.error('Pass an explicit path, for example:');
    console.error(`  slope review ${relative(cwd, scorecards[scorecards.length - 1])}`);
    console.error('');
    process.exit(1);
  }
  return scorecards[0];
}

/** Marker prefix distinguishing slope-generated reviews from project-authored
 *  ones. The full first line carries a content hash of the body, so a
 *  generated file counts as regenerable only while it is PRISTINE: a
 *  human-edited generated review keeps the marker but fails the hash and is
 *  protected like an authored file, and an authored file that merely quotes
 *  the marker elsewhere never matches, because only line 1 is consulted. */
export const REVIEW_GENERATED_MARKER = '<!-- generated by slope review';

const MARKER_LINE_PATTERN = /^<!-- generated by slope review; content-hash: ([0-9a-f]{16}) -->$/;

function reviewBodyHash(body: string): string {
  return createHash('sha256').update(body, 'utf8').digest('hex').slice(0, 16);
}

function renderGeneratedReview(review: string): string {
  const body = `\n${review}\n`;
  return `<!-- generated by slope review; content-hash: ${reviewBodyHash(body)} -->${body}`;
}

/** True only for a byte-pristine slope-generated review file. */
export function isPristineGeneratedReview(content: string): boolean {
  const firstNewline = content.indexOf('\n');
  if (firstNewline < 0) return false;
  const match = MARKER_LINE_PATTERN.exec(content.slice(0, firstNewline));
  if (!match) return false;
  return reviewBodyHash(content.slice(firstNewline)) === match[1];
}

/** Repair UTF-8 bytes that were decoded as cp1252 somewhere upstream (#616). */
const MOJIBAKE_REPAIRS: Array<[RegExp, string]> = [
  [/â€”/g, '—'], // â€” -> em dash
  [/â€“/g, '–'], // â€“ -> en dash
  [/â€™/g, '’'], // â€™ -> right single quote
  [/â€˜/g, '‘'], // â€˜ -> left single quote
  [/â€œ/g, '“'], // â€œ -> left double quote
  [/â€[\u009d\ufffd]/g, '”'], // right double quote; 0x9D is unmapped in cp1252 and survives raw or as U+FFFD
  [/â€¦/g, '…'], // â€¦ -> ellipsis
  [/Â /g, ' '],            // Â  -> non-breaking space artifact
];

export function repairMojibake(text: string): string {
  return MOJIBAKE_REPAIRS.reduce((current, [pattern, replacement]) => current.replace(pattern, replacement), text);
}

/** A bare sprint selector: `259`, `S259`, `146.1`. */
const SPRINT_SELECTOR_RE = /^S?\d+(?:\.\d+)?$/i;

export interface ParsedReviewArgs {
  path?: string;
  sprintSelector?: string;
  mode?: string;
  metaphor?: string;
  /** `null` means --stdout; `undefined` means the default output path. */
  outputPath?: string | null;
  force: boolean;
}

/** Parse `slope review` arguments.
 *
 *  Accepts `--sprint=N`, `--sprint N` and a bare positional `N`. Only the
 *  equals form used to work: with the other two the number fell through to
 *  the path argument and was reported as `Failed to parse <cwd>/N` (#689).
 */
export function parseReviewArgs(args: string[]): ParsedReviewArgs {
  const metaphorArg = args.find(a => a.startsWith('--metaphor='));
  const outputArg = args.find(a => a.startsWith('--output='));

  let sprintSelector: string | undefined;
  // Index of an argument consumed as a flag's value, so it is not also
  // read as the positional path.
  let consumedValue = -1;

  const equalsForm = args.find(a => a.startsWith('--sprint='));
  if (equalsForm) {
    sprintSelector = equalsForm.slice('--sprint='.length);
  } else {
    const flagAt = args.indexOf('--sprint');
    const value = flagAt === -1 ? undefined : args[flagAt + 1];
    if (value != null && !value.startsWith('--')) {
      sprintSelector = value;
      consumedValue = flagAt + 1;
    }
  }

  let path = args.find((a, i) => !a.startsWith('--') && i !== consumedValue);

  // A bare number is a sprint, not a file. Anything else stays a path, so
  // `slope review docs/retros/sprint-259.json` is unaffected.
  if (sprintSelector === undefined && path !== undefined && SPRINT_SELECTOR_RE.test(path)) {
    sprintSelector = path;
    path = undefined;
  }

  return {
    path,
    sprintSelector,
    mode: args.includes('--plain') ? 'plain' : undefined,
    metaphor: metaphorArg?.slice('--metaphor='.length),
    outputPath: args.includes('--stdout') ? null : outputArg?.slice('--output='.length),
    force: args.includes('--force'),
  };
}

export function reviewCommand(
  path?: string,
  mode?: string,
  metaphorFlag?: string,
  outputPath?: string | null,
  sprintSelector?: string,
  options: { force?: boolean } = {},
): void {
  const config = loadConfig();
  const cwd = process.cwd();
  const metaphor = resolveMetaphor(metaphorFlag ? [`--metaphor=${metaphorFlag}`] : [], config.metaphor);
  const scorecardPath = resolveScorecardPath(path, sprintSelector, cwd, config);

  let raw: any;
  try {
    raw = JSON.parse(readFileSync(scorecardPath, 'utf8'));
  } catch {
    console.error(`\nFailed to parse ${scorecardPath}\n`);
    process.exit(1);
  }

  const card: GolfScorecard = normalizeScorecard(raw);

  const reviewMode = mode === 'plain' ? 'plain' : 'technical';
  // Repair at the source so stdout and the written file always match.
  const rawReview = formatSprintReview(card, undefined, undefined, reviewMode, metaphor);
  const review = repairMojibake(rawReview);
  if (review !== rawReview) {
    console.error('Note: repaired cp1252-mangled character sequences from scorecard data (#616).');
  }
  console.log('');
  console.log(review);

  // The content the gate check should validate: whatever ends up on disk.
  let reviewOnDisk = `${review}\n`;
  if (outputPath !== null) {
    const reviewPath = outputPath
      ? isAbsolute(outputPath) ? outputPath : join(cwd, outputPath)
      : join(dirname(scorecardPath), `sprint-${card.sprint_number}-review.md`);
    const nextContent = renderGeneratedReview(review);
    const existing = existsSync(reviewPath) ? readFileSync(reviewPath, 'utf8') : null;
    if (existing != null
      && existing !== nextContent
      && !options.force
      && !isPristineGeneratedReview(existing)) {
      // Anything that is not a byte-pristine generated file may carry human
      // work — project-authored reviews AND hand-enriched generated ones;
      // silently replacing either destroys work (#616).
      console.error(`\nRefusing to overwrite existing review: ${relative(cwd, reviewPath)}`);
      console.error('It is not a pristine slope-generated file, so it may carry project-authored content.');
      console.error('Keep it (it still satisfies the review_md gate, subject to required sections),');
      console.error('re-run with --force to replace it, or use --stdout / --output=<path>.');
      reviewOnDisk = existing;
    } else if (existing === nextContent) {
      console.error(`\nReview unchanged: ${relative(cwd, reviewPath)}`);
      reviewOnDisk = existing;
    } else {
      mkdirSync(dirname(reviewPath), { recursive: true });
      writeFileSync(reviewPath, nextContent);
      console.error(`\nReview written: ${relative(cwd, reviewPath)}`);
      reviewOnDisk = nextContent;
    }
  }

  // Generating a historical sprint's review must not complete a different
  // active sprint's gate, and view-only runs (--stdout, --output=<custom>)
  // must not mutate gate state at all — only a canonical-path run validates
  // what closeout will actually ship.
  const sprintState = loadSprintState(cwd);
  if (outputPath === undefined && sprintState && sprintIdsEqual(sprintState.sprint, card.sprint_number)) {
    // User-supplied config: tolerate any shape without crashing closeout.
    const configuredSections = config.reviewRequiredSections;
    if (configuredSections != null && !Array.isArray(configuredSections)) {
      console.error('\nIgnoring reviewRequiredSections: expected an array of heading strings.');
    }
    const requiredSections = Array.isArray(configuredSections)
      ? configuredSections.filter((section): section is string => typeof section === 'string' && section.trim() !== '')
      : [];
    // Match required headings against whole lines, so prose that merely
    // mentions a heading cannot satisfy the gate.
    const reviewLines = reviewOnDisk.toLowerCase().split('\n').map(line => line.trim());
    const missing = requiredSections.filter(section =>
      !reviewLines.some(line => line.startsWith(section.trim().toLowerCase())));
    if (missing.length > 0) {
      // Reopen the gate rather than merely refusing to close it: a --force
      // regeneration may have replaced a compliant review with a bare one.
      updateGate(cwd, 'review_md', false);
      console.error(`\nreview_md gate reopened — required section(s) missing from the review: ${missing.join(', ')}`);
    } else {
      updateGate(cwd, 'review_md', true);
    }
  }
}

export const reviewCommandInternals = {
  discoverScorecardPaths,
  resolveScorecardPath,
};
