import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { parseRoadmap, extractHazardIndex, loadScorecards, formatSprintLabel, formatSprintNumber, parseSprintNumber } from '../../core/index.js';
import type { RoadmapDefinition, RoadmapSprint } from '../../core/index.js';
import { loadConfig } from '../config.js';

/**
 * `slope sprint plan --sprint=N [--output=path]` — generate a markdown
 * implementation plan from roadmap + vision + recent hazards.
 *
 * Implements GH #312. Pairs with `slope sprint begin` (S88-3) which
 * surfaces "next ticket" but not the full plan.
 *
 * Output sections:
 *   - Objective (sprint theme)
 *   - Tickets (table with key/title/club/complexity)
 *   - Dependencies (sprint depends_on + completed status)
 *   - Recommended order (intra-sprint depends_on resolution)
 *   - Required gates
 *   - Hazards (filtered by sprint scope keywords)
 *   - Acceptance criteria stub
 *   - Suggested commit boundaries
 */
export async function sprintPlanCommand(args: string[]): Promise<void> {
  const sprintArg = args.find(a => a.startsWith('--sprint='));
  const outputArg = args.find(a => a.startsWith('--output='));

  if (!sprintArg) {
    console.error('\nUsage: slope sprint plan --sprint=N [--output=<path>]\n');
    console.error('  --sprint=N      Sprint number to generate plan for (required)');
    console.error('  --output=<path> Where to write the plan (default: docs/backlog/sprint-N-plan.md)\n');
    process.exit(1);
  }

  const sprintId = parseSprintNumber(sprintArg.slice('--sprint='.length));
  if (!sprintId) {
    console.error('Error: --sprint must be a positive sprint id, e.g. 114 or 114.5');
    process.exit(1);
  }

  const cwd = process.cwd();
  const config = loadConfig(cwd);

  // Load roadmap
  const roadmapAbs = join(cwd, config.roadmapPath);
  if (!existsSync(roadmapAbs)) {
    console.error(`No roadmap found at ${config.roadmapPath}. Run \`slope roadmap generate\` first.`);
    process.exit(1);
  }
  let roadmap: RoadmapDefinition | null;
  try {
    roadmap = parseRoadmap(JSON.parse(readFileSync(roadmapAbs, 'utf8'))).roadmap;
  } catch (err) {
    console.error(`Failed to parse roadmap: ${(err as Error).message}`);
    process.exit(1);
  }
  if (!roadmap) {
    console.error(`Roadmap has structural issues; run \`slope roadmap validate\`.`);
    process.exit(1);
  }

  const sprint = roadmap.sprints.find(s => s.id === sprintId);
  if (!sprint) {
    console.error(`Sprint ${formatSprintLabel(sprintId)} not found in roadmap.`);
    process.exit(1);
  }

  // Hazard context — pull recent hazards from scorecards
  let hazardLines: string[] = [];
  try {
    const scorecards = loadScorecards(config, cwd);
    const idx = extractHazardIndex(scorecards);
    hazardLines = [
      ...idx.shot_hazards.slice(0, 8).map(h => `- [S${h.sprint}] ${h.type}: ${h.description}`),
      ...idx.bunker_locations.slice(0, 5).map(b => {
        // Defend against strings, plain objects, AND null/undefined — typeof
        // null is 'object', so the previous cast would throw on null entries.
        let label: string;
        if (typeof b === 'string') {
          label = b;
        } else if (b && typeof b === 'object') {
          const obj = b as { area?: string; location?: string };
          label = obj.location ?? obj.area ?? JSON.stringify(b);
        } else {
          label = String(b);
        }
        return `- bunker: ${label}`;
      }),
    ];
  } catch { /* hazards optional */ }

  // Render
  const md = renderSprintPlan(sprint, roadmap, hazardLines);

  // Output path — use resolve() so an absolute --output=/tmp/... is honored
  // verbatim instead of being silently coerced to a repo-relative path
  // (#341). join(cwd, '/tmp/x') drops the leading slash; resolve() doesn't.
  const outputPath = outputArg
    ? outputArg.slice('--output='.length)
    : `docs/backlog/sprint-${formatSprintNumber(sprintId)}-plan.md`;
  const outputAbs = resolve(cwd, outputPath);

  mkdirSync(dirname(outputAbs), { recursive: true });
  writeFileSync(outputAbs, md);

  // Report the resolved absolute path so the user knows exactly where the
  // file landed — the previous "Wrote <relative>" form was misleading when
  // an absolute path got rewritten.
  console.log(`Wrote ${outputAbs}`);
  console.log(`  Tickets: ${sprint.tickets.length}`);
  console.log(`  Par: ${sprint.par} | Slope: ${sprint.slope}`);
}

export function renderSprintPlan(
  sprint: RoadmapSprint,
  roadmap: RoadmapDefinition,
  hazardLines: string[],
): string {
  const lines: string[] = [];
  lines.push(`# Sprint ${formatSprintNumber(sprint.id)} Plan — ${sprint.theme}`);
  lines.push('');
  lines.push('<!-- Generated by `slope sprint plan`. Regenerate when roadmap or hazards change. -->');
  lines.push('');
  lines.push(`**Par:** ${sprint.par}  |  **Slope:** ${sprint.slope}  |  **Type:** ${sprint.type}`);
  lines.push('');

  // Objective
  lines.push('## Objective');
  lines.push('');
  lines.push(sprint.theme);
  lines.push('');

  // Tickets
  lines.push('## Tickets');
  lines.push('');
  lines.push('| Key | Title | Club | Complexity | Depends on |');
  lines.push('|---|---|---|---|---|');
  for (const t of sprint.tickets) {
    const deps = (t.depends_on ?? []).join(', ') || '—';
    lines.push(`| ${t.key} | ${t.title} | ${t.club} | ${t.complexity} | ${deps} |`);
  }
  lines.push('');

  // Sprint dependencies
  if (sprint.depends_on && sprint.depends_on.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    const completedIds = new Set(
      roadmap.sprints
        .filter(s => (s as RoadmapSprint & { status?: string }).status === 'complete')
        .map(s => s.id),
    );
    for (const d of sprint.depends_on) {
      const status = completedIds.has(d) ? 'complete' : 'pending';
      lines.push(`- ${formatSprintLabel(d)} (${status})`);
    }
    lines.push('');
  }

  // Recommended order — topological sort of intra-sprint depends_on
  const order = topologicalOrder(sprint.tickets);
  if (order.length > 0) {
    lines.push('## Recommended order');
    lines.push('');
    for (let i = 0; i < order.length; i++) {
      lines.push(`${i + 1}. ${order[i]}`);
    }
    lines.push('');
  }

  // Required gates
  lines.push('## Required gates');
  lines.push('');
  lines.push('Before marking the sprint complete:');
  lines.push('- tests');
  lines.push('- code_review');
  lines.push('- architect_review');
  lines.push('- scorecard');
  lines.push('- review_md');
  lines.push('');

  // Required checks
  lines.push('## Required checks before commit');
  lines.push('');
  lines.push('- `pnpm typecheck` (or project-equivalent)');
  lines.push('- `pnpm test` (or project-equivalent)');
  lines.push('- `slope roadmap validate`');
  lines.push('- `slope commit-ready`');
  lines.push('');

  // Hazards
  lines.push('## Hazards');
  lines.push('');
  if (hazardLines.length === 0) {
    lines.push('_No recent hazards on file. Consult `slope briefing --keywords=...` for area-specific gotchas._');
  } else {
    for (const h of hazardLines) lines.push(h);
  }
  lines.push('');

  // Acceptance criteria stub
  lines.push('## Acceptance criteria');
  lines.push('');
  lines.push('Each ticket lands on `main` via PR with:');
  lines.push('- typecheck + tests green');
  lines.push('- review-amend findings recorded');
  lines.push('- scorecard validated');
  lines.push('');

  // Commit boundaries
  lines.push('## Suggested commit boundaries');
  lines.push('');
  lines.push('One commit per ticket; bundled-commit only when tickets share files and tests run together. Conventional-commit prefix mirrors ticket type (feat/fix/chore).');
  lines.push('');

  return lines.join('\n');
}

/** Kahn's-algorithm topological sort over intra-sprint ticket dependencies.
 *  Falls back to insertion order when any tickets have a cycle or external dep. */
function topologicalOrder(tickets: Array<{ key: string; depends_on?: string[] }>): string[] {
  const keys = new Set(tickets.map(t => t.key));
  const inDegree = new Map<string, number>();
  const edges = new Map<string, string[]>();

  for (const t of tickets) {
    inDegree.set(t.key, 0);
    edges.set(t.key, []);
  }
  for (const t of tickets) {
    for (const dep of t.depends_on ?? []) {
      if (!keys.has(dep)) continue; // skip external deps
      edges.get(dep)?.push(t.key);
      inDegree.set(t.key, (inDegree.get(t.key) ?? 0) + 1);
    }
  }

  const ready = tickets.filter(t => (inDegree.get(t.key) ?? 0) === 0).map(t => t.key);
  const order: string[] = [];
  while (ready.length > 0) {
    const k = ready.shift()!;
    order.push(k);
    for (const next of edges.get(k) ?? []) {
      const newDeg = (inDegree.get(next) ?? 0) - 1;
      inDegree.set(next, newDeg);
      if (newDeg === 0) ready.push(next);
    }
  }

  // Cycle or missing — fall back to insertion order
  if (order.length !== tickets.length) {
    return tickets.map(t => t.key);
  }
  return order;
}
